name: lab3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/beef.jpeg
    - images/brownies.jpg
    - images/chcicken.webp
    - images/cookies.jpg
    - images/crockpot.webp
    - images/icecream.jpg
    - images/maindish.jpeg
    - images/pie.jpg
    - images/pork.webp
    - images/salad.webp
    - images/seafood.jpeg
    - images/sidedish.webp
